# Use root/example as user/password credentials
# docker stack deploy -c stack.yml bookstore
version: '3.1'

services:

  db:
    image: mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: users_db

  adminer:
    image: adminer:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    ports:
      - 8081:8080

  cassandra:
    image: cassandra:3.11
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "host.docker.internal"
    deploy:
      restart_policy:
        condition: on-failure
        window: 120s
    ports:
      - 7000-7001:7000-7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    volumes:
      - cassandradb:/var/lib/cassandra

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
#    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es02,es03
#      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

volumes:
  mysqldb:
  cassandradb:
  elasticdata:
    driver: local

networks:
  elastic:
#    driver: bridge