# Use root/example as user/password credentials
# docker stack deploy -c stack.yml mysql
version: '3.1'

services:

  db:
    image: mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: users_db

  adminer:
    image: adminer:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    ports:
      - 8081:8080

  cassandra:
    image: cassandra:3.11
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "host.docker.internal"
    deploy:
      restart_policy:
        condition: on-failure
        window: 120s
    ports:
      - 7000-7001:7000-7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    volumes:
      - cassandradb:/var/lib/cassandra

volumes:
  mysqldb:
  cassandradb: